### ISSUE TITLE
The method getResponsiveSteps of the FormLayout does not return the declared type

### ISSUE THREAD

**Issue by appreciated** [vaadin/vaadin-flow-components#392] opened 2020-11-15 15:58 UTC
The method `getResponsiveSteps` returns another type than declared.

```
public List<ResponsiveStep> getResponsiveSteps() {
    JsonArray stepsJsonArray = (JsonArray) getElement()
            .getPropertyRaw("responsiveSteps");
    if (stepsJsonArray == null) {
        return Collections.emptyList();
    }
    List<ResponsiveStep> steps = new ArrayList<>();
    for (int i = 0; i < stepsJsonArray.length(); i++) {
        steps.add(stepsJsonArray.get(i));
    }
    return steps;
}
```

### Expected behaviour:
The method should return a `List` of `ResponsiveStep` objects 

### Actual behaviour:
The method returns a `List` of `JsonObject` objects.

**Comment by tomivirkki** [comment] 2020-11-24 11:46
Closing as a duplicate of https://github.com/vaadin/vaadin-form-layout/issues/135

**Closed by tomivirkki** 2020-11-24 11:46 UTC
