### ISSUE TITLE
ComboBox FetchCallback looses the filter when scrolling the dropdown

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-flow-components#388] opened 2020-11-13 07:45 UTC
Vaadin 18.0.0.beta2

The attached code when I type `1` in the combo box returns
```
Count is 176; filter: 1
Return 50 items from 0; filter: 1
Return 50 items from 50; filter: null
Return 50 items from 100; filter: null
Return 50 items from 150; filter: null
```

code

```java
import java.util.ArrayList;
import java.util.Optional;
import java.util.stream.Stream;

import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.provider.Query;
import com.vaadin.flow.router.Route;

@Route("lazycombo")
public class LazyCombo extends VerticalLayout {
	static final ArrayList<String> list = new ArrayList<>();
	static final int MAX_ITEMS = 500;
	static {
		for (int i = 1; i <= MAX_ITEMS; i++) {
			list.add(String.valueOf(i));
		}
	}

	public LazyCombo() {
		ComboBox<String> combo = new ComboBox<>();
		combo.setItems(this::items, this::count);
		add(combo);
	}

	private int count(Query<String, String> q) {
		int count = (int) filteredItems(q).count();
		System.out.println(String.format("Count is %s; filter: %s", count, q.getFilter().isPresent() ? q.getFilter().get() : "null"));
		return count;

	}

	private Stream<String> items(Query<String, String> q) {
		System.out.println(String.format("Return %s items from %s; filter: %s", q.getLimit(), q.getOffset(), q.getFilter().isPresent() ? q.getFilter().get() : "null"));
		return filteredItems(q).skip(q.getOffset()).limit(q.getLimit());
	}
	
	private Stream<String> filteredItems(Query<String, String> q) {
		return list.stream().filter(item -> doFilter(item, q.getFilter()));
	}

	private boolean doFilter(String item, Optional<String> filter) {		
		if (filter.isEmpty()) {
			return true;
		} else {
			return item.contains(filter.get());	
		}
		
	}
}
```

**Comment by mshabarov** [comment] 2020-11-13 09:34
This is actually a regression after applying the lazy loading with unknown size. The filter sent by `ComboBox` to `DataCommunicator` is used for that single request and then erased so as to not impact the data view API (getItemCount/getItem/getItems/addItemCountListener), because the client-side filter is treated as ‘disposable’ and will disappear anyway when the user closes dropdown. So, the problem is that `ComboBox` does not erase this filter internally, but `DataCommunicator` does. Then, `ComboBox` compares the last sent filter (for first page) with the newly sent filter (for second, third page, and so on), and it sees they are equals and does to update the filter in `DataCommunicator`. As a result, the `DataCommunicator` uses empty filter for second and further pages.

The proposed fix is in checking that the filter from client is not empty, and if not, then anyway send it to `DataCommunicator`:

Current version:
```java
        filterSlot = filter -> {
            if (!Objects.equals(filter, lastFilter)) {
                // DataCommunicator filter slot invokation
                // ...
                lastFilter = filter;
            }
        };
```

With patch:
```java
        filterSlot = filter -> {
            // Send filter to data communicator if it's not empty, even though it is the same as previously sent,
            // since the data communicator treated it as disposable and erases it after each request.
            if (!Objects.equals(filter, lastFilter) || !filter.isEmpty()) {
                // DataCommunicator filter slot invokation
                // ...
                lastFilter = filter;
            }
        };
```

**Closed** 2020-11-18 16:54 UTC
