### ISSUE TITLE
Combo Box with ComponentRenderer: options disappearing when searching and selecting them.

### ISSUE THREAD

**Issue by DavidKoenig** [vaadin/vaadin-flow-components#437] opened 2020-11-24 10:31 UTC
### Description of the bug / feature
If you use the Combo Box with a ComponentRenderer the options are disappearing in the selection list when first searching and then selecting them.
This only appears when using Vaadin on the Java side, HTML doesn't seem to produce this bug. 
### Minimal reproducible example
Can be found at your own site: https://vaadin.com/components/vaadin-combo-box/java-examples/presentation 
### Expected behavior
Options don't disappear.
### Actual behavior
Like described, the option is disappearing when searching and selecting it. The rendered HTML element of the option is actually cleared in the dom.
### Versions:
    - Vaadin / Flow version: 14.4.2
    - Java version: 11.0.7
    - OS version: Windows 10
    - Browser version: Chrome 83.0.4103.116, Firefox 78.5.0esr (64-Bit)
    - Application Server: Spring Boot 2.3.3 embedded
    - IDE IntelliJ IDEA:

**Comment by tomivirkki** [comment] 2020-12-01 11:45
Duplicate of https://github.com/vaadin/vaadin-combo-box/issues/945

**Comment by DiegoCardoso** [comment] 2021-01-11 09:04
This bug is due a combination of how `iron-list` in `vaadin-combo-box` and `flow-component-renderer` work. I will try to explain them briefly:

#### `iron-list`

`iron-list` generates the DOM elements based on the template and assign each `item` from its `items` list to each element:
| `items` |
|---|
| aaaa |
| bbbb |
| cccc |
| dddd |

If, then, a subset of items is set to `iron-list` (eg., user uses the filter on `ComboBox`), it won't move the DOM elements to appear at the top, but rather, it will set each `item` to the first few elements and hide everything else.

So, on the previous example, if user types `d`:
| `items` (no filter) | `item` (filter: _d_) |
|---| ---|
| aaaa | dddd |
| bbbb | bbbb (_hidden_) |
| cccc | cccc (_hidden_) |
| dddd | dddd (_hidden_) |

_Note that the last item is still "holding" `dddd`, but hidden_

When the `items` is restored to the original value (eg, user clear the filter on `ComboBox`), then `iron-list` will set the items again to the elements.

| `items` (filter: d) | `item` (no filter) |
|---| ---|
| dddd | aaaa |
| bbbb (_hidden_) | bbbb |
| cccc (_hidden_) | cccc |
| dddd (_hidden_) | dddd |

Effectively, only the first item will be actually set and send down to the element, since for all the other ones, the `item` hasn't changed since the previous state, just the visibility (_this is also important to note for the `flow-component-renderer`_).

#### `flow-component-renderer`
_(there could be some imprecision and the explanation is quite simplified)_

`FCR` cares about two values: `appid` and `nodeid`. For each item, a DOM tree will be generated, based on the template, from the server but it won't immediately be attached to the `ComboBox`. When the `FCR` is attached, then it will look for the node associated with its `nodeid` and append it.

### About the bug

**Comment by DiegoCardoso** [comment] 2021-01-11 09:34
This bug is due a combination of how `iron-list` in `vaadin-combo-box` and `flow-component-renderer` work. I will try to explain them briefly:

#### `iron-list`

`iron-list` generates the DOM elements based on the template and assign each `item` from its `items` list to each element:
| `items` |
|---|
| aaaa |
| bbbb |
| cccc |
| dddd |

If, then, a subset of items is set to `iron-list` (eg., user uses the filter on `ComboBox`), it won't move the DOM elements to appear at the top, but rather, it will set each `item` to the first few elements and hide everything else.

So, on the previous example, if user types `d`:
| `items` (no filter) | `item` (filter: _d_) |
|---| ---|
| aaaa | dddd |
| bbbb | bbbb (_hidden_) |
| cccc | cccc (_hidden_) |
| dddd | dddd (_hidden_) |

_Note that the last item is still "holding" `dddd`, but hidden_

When the `items` is restored to the original value (eg, user clear the filter on `ComboBox`), then `iron-list` will set the items again to the elements.

| `items` (filter: d) | `item` (no filter) |
|---| ---|
| dddd | aaaa |
| bbbb (_hidden_) | bbbb |
| cccc (_hidden_) | cccc |
| dddd (_hidden_) | dddd |

Effectively, only the first item will be actually set and send down to the element, since for all the other ones, the `item` hasn't changed since the previous state, just the visibility (_this is also important to note for the `flow-component-renderer`_).

#### `flow-component-renderer`
_(there could be some imprecision and the explanation is quite simplified)_

`FCR` cares about two values: `appid` and `nodeid`. For each item, a DOM tree will be generated, based on the template, from the server but it won't immediately be attached to the `ComboBox`. When the `FCR` is attached, then it will look for the node associated with its `nodeid` and append it.

### About the bug

So, here are the steps that will produce the bug:
1. `ComboBox` is opened
1. For each `item`, a DOM tree is created base on the template and a `flow-component-renderer` holding the reference to the node is attached to the `vaadin-combo-box-item`
1. When `flow-componente-renderer` is attached, it will look to its `nodeid` and attach the element associated with it to itself
1. **USER FILTERS THE COMBOBOX** 
1. As mentioned before, `iron-list` will set each filtered item to the first few elements
1. When that happens, the first few `flow-component-renderer`s will receive new `nodeid`s, which are already associated with other `FCR`s
1. Once a new `nodeid` is received, `FCR` will look and **append the node tree to itself**, which essentially removes this node from the original `FCR`
1. **USER CLEARS THE FILTER**
1. `iron-list` will reset the `items` to their original positions, but effectively only the ones that had been changed will receive the new `item` while the other ones will only be unhidden.
1. _Because of that_ the `FCR`s from which the elements were originally attached won't receive any update, therefore, **remaining empty**

### Solution proposal

One solution would be to change how `ComboBox` behaves with the filtered out items to not only be hidden but also have it cleared (by setting `null`, for instance), so when the elements are restored, the hidden ones would also get updated and `FCR` would be able to reattach the node to its original position. But that would be a breaking change, since the template would start receiving `null` values when they didn't use to.

That's why we would propose to make a change on `FCR` to have a similar [approach as done on Grid](https://github.com/vaadin/vaadin-grid/blob/master/src/vaadin-grid.js#L845), which uses an "appear listener" based on CSS animation to call its `_attachRenderedComponentIfAble` when the element gets unhidden to be able to reattach the node to its original position.

**Comment by tulioag** [comment] 2021-02-10 07:43
Should be fixed by https://github.com/vaadin/flow/pull/9783

**Comment by web-padawan** [comment] 2021-02-16 11:06
The PR linked above is now merged, closing as fixed. Note the fix would need to be cherry-picked to older Flow versions.

**Closed by web-padawan** 2021-02-16 11:06 UTC
Labels: BFP, vaadin-combo-box

**Comment by DavidKoenig** [comment] 2021-02-16 12:21
Thank you guys! I'm looking forward to a backport/ cherry-pick to v14.x.
