### ISSUE TITLE
formLayout.getResponsiveSteps() list elements cannot be cast to ResponsiveStep

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-flow-components#740] opened 2021-03-18 13:25 UTC
```
private static void dumpResponsiveSteps(FormLayout formLayout){
        List<FormLayout.ResponsiveStep> steps = formLayout.getResponsiveSteps();
        for (FormLayout.ResponsiveStep step : steps){
            System.err.println(step.toString() + " : " + step.getClass().getCanonicalName());
        }
        System.err.println(steps.size() + " responsive steps defined.");
    }
```
gives me

Caused by: java.lang.ClassCastException: class elemental.json.impl.JreJsonObject cannot be cast to class com.vaadin.flow.component.formlayout.FormLayout$ResponsiveStep (elemental.json.impl.JreJsonObject and com.vaadin.flow.component.formlayout.FormLayout$ResponsiveStep are in unnamed module of loader 'app')
	at com.example.application.views.layouting.LayoutingView.dumpResponsiveSteps(LayoutingView.java:86

I am a bit puzzled but also lack the time to investigate further.

Vaadin 14.4.9

**Comment by enver-haase** [comment] 2021-03-19 12:50
Heap pollution?
https://stackoverflow.com/questions/12462079/possible-heap-pollution-via-varargs-parameter

**Comment by TatuLund** [comment] 2021-03-19 14:47
This seems to be duplicate of https://github.com/vaadin/vaadin-form-layout/issues/135

As a workaround you can use EnhancedFormLayout v1.0.1 from Directory

**Comment by web-padawan** [comment] 2021-03-19 14:52
Closing per above comment as duplicate.

**Closed by web-padawan** 2021-03-19 14:52 UTC
