### ISSUE TITLE
MultiComboBox filter event exception

### ISSUE THREAD

**Issue by sunyoran** [vaadin/vaadin-flow-components#744] opened 2021-03-22 08:57 UTC
A base usage of MultiComboBox as below:

![image](https://user-images.githubusercontent.com/46042932/111964095-35f67480-8b2f-11eb-8563-cbc7c579bd8b.png)

Step 1.  I filter an accurately item 'A01' as below:

![image](https://user-images.githubusercontent.com/46042932/111964253-60e0c880-8b2f-11eb-8f9a-8e9a7932e60d.png)

Step 2. and then, click the popup option item as below:

![image](https://user-images.githubusercontent.com/46042932/111964422-8d94e000-8b2f-11eb-80a1-461e2abc0f4a.png)

Step 3. click mouse anywhere out of MultiComboBox, the strange behavior happened, MultiComboBox will clear.

**Comment by TatuLund** [comment] 2021-03-22 09:07
If this issue is about https://vaadin.com/directory/component/multicombobox-component, the correct place for the issue is

https://github.com/vaadin-component-factory/multi-combo-box-flow/issues

**Comment by sunyoran** [comment] 2021-03-22 09:31
Thanks, I have reported it in vaadin-component-factory repository.
https://github.com/vaadin-component-factory/multi-combo-box-flow/issues/17

**Comment by tulioag** [comment] 2021-03-22 09:43
Closed in favor of https://github.com/vaadin-component-factory/multi-combo-box-flow/issues/17

**Closed by tulioag** 2021-03-22 09:43 UTC
